name: sciapy

channels:
    - conda-forge

dependencies:
    - python=3
    - numpy<1.22
    - pybind11
    - celerite
    - george
    - nbsphinx
    - numpydoc
    - ipython
    - pip
    - pip:
        - sphinx-markdown-tables
