name: sciapy

channels:
    - conda-forge

dependencies:
    - python=3.6
    - numpy
    - pybind11
    - celerite
    - george
    - numpydoc
    - ipython
    - pip
    - pip:
        - sphinx-markdown-tables
