language: python
cache: pip
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
addons:
  apt:
    packages:
      - libhdf5-dev
      - libnetcdf-dev
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install "numpy>=1.13.0"
  - pip install pybind11
  - pip install -U pytest pytest-cov codecov coveralls
  - pip install tox-travis
  - pip install scrutinizer-ocular
  - pip install "astropy<4.0"
  - pip install -e ".[all]"
script:
  - py.test -v --cov sciapy
after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      codecov
      coveralls
      ocular --data-file ".coverage"
    fi
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: __token__
    password:
      secure: jkxwuahmZqMa0JRnKz5mpaD1HJxiEZhRuvSKwWOZU2UHoH+zRmH10c/ZGM80GPSrbS6Mju69oXTBOzb9IRnPDZeOZgrSbnVjVx5eYmmawwz25hcnnW2g4Zy/YZuXaA+uij1MxzkeaCVotLRSVkYLlkZ+zxP+6uD+EIRSkEbwMKBnQzPgQzFPb32EagCC1p/P6arTBDJm+ZKplhX3KOpAnj9VQcWVEMWk5sz8EoUBe5njEbdKgbzW2cAfT9TQsEVXNfALnh529oewKRR/yVrahLcjRSWi00TK+9weJCXSyUHwHklMG3KSj2ineKUjesxY1aaS6EJUBGkH/PGGjMvgweetD3y+wePKoVr/J5DU3mgauvHrmmH56t1BTOqmQmGRo7/w18s8Vue8Y96USaUWBa4m5M3w3JGdCAVrE7XVqS8qcJ/2J7kPEkUF6ed4w6IUPl11DExyBzQWIQK0ApOhw+w2vJMRP8jSQwVkgXxXyePX6Ap6U4lnc985KpKliLXSXTCw8e1dltQAXbaONU9fetNTilBfdmQvhZ2LJ/hSKSDEKvz2MHZQMecy01/doxGH3gEz7WcMZ740bc8FZh4k3h//DNs3GVBaaA9DVKEIMCvF8oaG27PZCG7gFZj/vi8AghraxRy2GROIZpG0o9bs4b6Bf1Z5xH2OOK0UWxIZnWk=
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      repo: st-bender/sciapy
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION == 3.7
