sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install pytest coveralls
  - pip install tox-travis
  - pip install .
script:
  - py.test -v
after_sucess: coveralls
notifications:
  email:
    on_success: never
    on_failure: always
