sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install pytest coveralls
  - "python setup.py install"
  - pip install tox-travis
script:
  - py.test -v
  - coverage run --source sciapy -m py.test
after_sucess: coveralls
notifications:
  email:
    on_success: never
    on_failure: always
