name: CI

on:
  push:
    branches:
      - master
      - github_ci

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - name: Install apt packages
        run: sudo apt-get install --no-install-recommends libhdf5-dev libnetcdf-dev netcdf-bin
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install configparser
          pip install h5py netcdf4
          pip install "numpy>=1.13.0,!=1.15.*"
          pip install pybind11
          pip install -U pytest "pytest-cov<2.9" codecov coveralls
          pip install scrutinizer-ocular
          pip install astropy
      - name: Install package
        run: |
          pip install -e ".[all]"
      - run: pip list
      - name: Test
        run: |
          py.test -v --cov sciapy
